from quprep.core.dataset import Dataset

class Scaler:
    strategy: str
    threshold: float

    def __init__(self, strategy: str = ..., threshold: float = ...) -> None: ...
    def fit(self, dataset: Dataset) -> Scaler: ...
    def transform(self, dataset: Dataset) -> Dataset: ...
    def fit_transform(self, dataset: Dataset) -> Dataset: ...

def auto_normalizer(encoding: str) -> Scaler: ...
